export default [
  {
    id: "1",
    title: "Apples x lb",
    price: 2.1,
    offerPrice: null,
    stock: 12,
    img: "apples.jpg",
    category: "Electrodomésticos",
  },
  {
    id: "0001",
    title: "Albendazol",
    price: 330,
    offerPrice: null,
    stock: 12,
    img: "Farmacia/Antimicrobianos/albendazol.png",
    category: "Farmacia",
  },
  {
    id: "9",
    title: "Azitromicina",
    price: 490,
    offerPrice: null,
    stock: 12,
    img: "Farmacia/Antimicrobianos/AZITROMICINA-500MG-CAJA-POR-3-TABLETAS-INCLINADO.jpg",
    category: "Farmacia",
  },
  {
    id: "2",
    title: "Amoxicilina",
    price: 350,
    offerPrice: null,
    stock: 12,
    img: "Farmacia/Antimicrobianos/amoxicilina.jpg",
    category: "Farmacia",
  },
  {
    id: "77",
    title: "Amoxicilina en Suspensión",
    price: 650,
    offerPrice: null,
    stock: 12,
    img: "Farmacia/Antimicrobianos/amoxicilina suspención.jpg",
    category: "Farmacia",
  },
  {
    id: "3",
    title: "Ciprofloxacino 500mg",
    price: 350,
    offerPrice: null,
    stock: 12,
    img: "Farmacia/Antimicrobianos/CIPROFLOXACINO-500-MG.jpg",
    category: "Farmacia",
  },
  {
    id: "4",
    title: "Cefalexina",
    price: 490,
    offerPrice: null,
    stock: 12,
    img: "Farmacia/Antimicrobianos/Cefalexina.jpg",
    category: "Farmacia",
  },
  {
    id: "888",
    title: "Cefalexina Suspensión",
    price: 750,
    offerPrice: null,
    stock: 12,
    img: "Farmacia/Antimicrobianos/cefalexina suspension.jpg",
    category: "Farmacia",
  },
  {
    id: "5",
    title: "Berry es feugiat mollis",
    price: 2.3,
    offerPrice: null,
    stock: 12,
    img: "berry.jpg",
    category: "Electrodomésticos",
  },
  {
    id: "6",
    title: "berry feugiat dui non mollis",
    price: 2.22,
    offerPrice: null,
    stock: 12,
    img: "berry2.jpg",
    category: "Electrodomésticos",
  },
  {
    id: "7",
    title: "Doxiciclina",
    price: 350,
    offerPrice: null,
    stock: 12,
    img: "Farmacia/Antimicrobianos/doxiciclina.jpg",
    category: "Farmacia",
  },
  {
    id: "7",
    title: "Diclofenaco + Paracetamol",
    price: 300,
    offerPrice: null,
    stock: 12,
    img: "Farmacia/Antiinflamatorios/Diclofenaco + Paracetamol.jpg",
    category: "Farmacia",
  },
  {
    id: "00012",
    title: "Fluconazol",
    price: 300,
    offerPrice: null,
    stock: 12,
    img: "Farmacia/Antimicrobianos/Fluconazol.jpg",
    category: "Farmacia",
  },
  {
    id: "000",
    title: "Ibuprofeno",
    price: 300,
    offerPrice: null,
    stock: 12,
    img: "Farmacia/Antiinflamatorios/ibuprofeno.jpg",
    category: "Farmacia",
  },
  {
    id: "000",
    title: "Mebendazol",
    price: 300,
    offerPrice: null,
    stock: 12,
    img: "Farmacia/Antimicrobianos/mebendazol.jpg",
    category: "Farmacia",
  },
  {
    id: "66",
    title: "Metronidazol 500mg",
    price: 300,
    offerPrice: null,
    stock: 12,
    img: "Farmacia/Antimicrobianos/METRONIDAZOL-500MG.jpg",
    category: "Farmacia",
  },
  {
    id: "66",
    title: "Paracetamol",
    price: 300,
    offerPrice: null,
    stock: 12,
    img: "Farmacia/Antiinflamatorios/paracetamol.jpg",
    category: "Farmacia",
  },
  {
    id: "8",
    title: "Sulfaprim",
    price: 310,
    offerPrice: null,
    stock: 12,
    img: "Farmacia/Antimicrobianos/sulfaprim.jpg",
    category: "Farmacia",
  },
  {
    id: "8",
    title: "Sulfaprim (Jarabe)",
    price: 900,
    offerPrice: null,
    stock: 12,
    img: "Farmacia/Antiinflamatorios/Sulfaprim Suspension.jpg",
    category: "Farmacia",
  },
  {
    id: "11",
    title: "cherry feugiat dui non mollis",
    price: 7.88,
    offerPrice: 6.88,
    stock: 12,
    img: "cherry.jpg",
    category: "Electrodomésticos",
  },
  {
    id: "22",
    title: "chicken feugiat dui non mollis",
    price: 4.88,
    offerPrice: null,
    stock: 12,
    img: "chicken.jpg",
    category: "meat",
  },
  {
    id: "33",
    title: "Aliquam feugiat non chicken",
    price: 8.88,
    offerPrice: null,
    stock: 12,
    img: "chicken2.jpg",
    category: "meat",
  },
  {
    id: "44",
    title: "clemen feugiat dui",
    price: 4.99,
    offerPrice: null,
    stock: 12,
    img: "clemen.jpg",
    category: "Electrodomésticos",
  },
  {
    id: "55",
    title: "cod feugiat dui non",
    price: 9.88,
    offerPrice: null,
    stock: 12,
    img: "cod.jpg",
    category: "meat",
  },
  {
    id: "88",
    title: "dates feugiat non duilis",
    price: 4.88,
    offerPrice: null,
    stock: 12,
    img: "dates.jpg",
    category: "Electrodomésticos",
  },
  {
    id: "99",
    title: "fresh fish feugiat dui",
    price: 4.88,
    offerPrice: null,
    stock: 12,
    img: "fish.jpg",
    category: "meat",
  },
  {
    id: "00",
    title: "fish lorem ipsum",
    price: 4.88,
    offerPrice: null,
    stock: 12,
    img: "fish2.jpg",
    category: "meat",
  },
  {
    id: "111",
    title: "fish non mollis feugiat dui",
    price: 4.88,
    offerPrice: 3.25,
    stock: 12,
    img: "fish3.jpg",
    category: "meat",
  },
  {
    id: "222",
    title: "lemon non mollis",
    price: 4.88,
    offerPrice: null,
    stock: 12,
    img: "lemon.jpg",
    category: "Electrodomésticos",
  },
  {
    id: "333",
    title: "Aliquam lime dui non mollis",
    price: 4.88,
    offerPrice: null,
    stock: 12,
    img: "lime.jpg",
    category: "Electrodomésticos",
  },
  {
    id: "444",
    title: "Aliquam mango dui non",
    price: 4.88,
    offerPrice: null,
    stock: 12,
    img: "mango.jpg",
    category: "Electrodomésticos",
  },
  {
    id: "555",
    title: "Aliquam meat dui non mollis",
    price: 4.88,
    offerPrice: null,
    stock: 12,
    img: "meat.jpg",
    category: "meat",
  },
  {
    id: "666",
    title: "meat feugiat dui non mollis",
    price: 4.88,
    offerPrice: 4.0,
    stock: 12,
    img: "meat2.jpg",
    category: "meat",
  },
  {
    id: "777",
    title: "Aliquam feugiat dui non meat",
    price: 4.88,
    offerPrice: null,
    stock: 12,
    img: "meat3.jpg",
    category: "meat",
  },
  {
    id: "999",
    title: "pears feugiat dui non mollis",
    price: 4.88,
    offerPrice: null,
    stock: 12,
    img: "pears.jpg",
    category: "Electrodomésticos",
  },
  {
    id: "1111",
    title: "Aliquam salmon dui non mollis",
    price: 4.88,
    offerPrice: null,
    stock: 12,
    img: "salmon.jpg",
    category: "meat",
  },

  {
    id: "bread1",
    title: "Sprouts Classic Seedsational Bread 14 oz",
    price: 2.25,
    offerPrice: null,
    stock: 12,
    img: "bread.jpg",
    category: "bakery",
  },
  {
    id: "bread2",
    title: "Traditional Corn Special Bread",
    price: 1.75,
    offerPrice: null,
    stock: 12,
    img: "bread2.jpg",
    category: "bakery",
  },
  {
    id: "bread3",
    title: "Sprouts Classic Seedsational Bread",
    price: 2.25,
    offerPrice: null,
    stock: 12,
    img: "bread3.jpg",
    category: "bakery",
  },
  {
    id: "toast",
    title: "Oven Baked Garlic & Cheese Toast",
    price: 1.7,
    offerPrice: null,
    stock: 12,
    img: "toast.jpg",
    category: "bakery",
  },
  {
    id: "toast2",
    title: "Oven Baked Italian Herb with Olive Oil Toast",
    price: 2.25,
    offerPrice: null,
    stock: 12,
    img: "toast2.jpg",
    category: "bakery",
  },
  {
    id: "cookies",
    title: "Raspberry Crumble Cookies",
    price: 2.25,
    offerPrice: null,
    stock: 12,
    img: "cookies.jpg",
    category: "bakery",
  },
  {
    id: "cookies2",
    title: "Chocolate Chip Cookies",
    price: 3.0,
    offerPrice: null,
    stock: 12,
    img: "cookies2.jpg",
    category: "bakery",
  },
  {
    id: "cookies3",
    title: "Freshly Baked Chocolate Chip Cookie",
    price: 2.5,
    offerPrice: null,
    stock: 12,
    img: "cookies3.jpg",
    category: "bakery",
  },
  {
    id: "muffin",
    title: "Thomas Cinnamon Raisin English Muffins",
    price: 2.25,
    offerPrice: null,
    stock: 12,
    img: "muffin.jpg",
    category: "bakery",
  },

  {
    id: "muffin2",
    title: "Mini Zucchini & Carrot Muffin",
    price: 2.25,
    offerPrice: null,
    stock: 12,
    img: "muffin2.jpg",
    category: "bakery",
  },

  {
    id: "muffin3",
    title: "Double Chocolate Oat Muffin ",
    price: 2.25,
    offerPrice: null,
    stock: 12,
    img: "muffin3.jpg",
    category: "bakery",
  },

  {
    id: "tea",
    title: "Freshly Brewed Organic Green Tea",
    price: 0.75,
    offerPrice: null,
    stock: 12,
    img: "tea.jpg",
    category: "drink",
  },

  {
    id: "coffe",
    title: "Fresh Grinded Frappé coffee",
    price: 1.5,
    offerPrice: null,
    stock: 12,
    img: "coffe.jpg",
    category: "drink",
  },

  {
    id: "coffe2",
    title: "Caffee Nero Mocha Late",
    price: 1.8,
    offerPrice: null,
    stock: 12,
    img: "coffe2.jpg",
    category: "drink",
  },

  {
    id: "coffe3",
    title: "Nescafe Clasico Instant Coffee",
    price: 2.2,
    offerPrice: null,
    stock: 12,
    img: "coffe3.jpg",
    category: "drink",
  },

  {
    id: "coffe4",
    title: "Peet Coffee Decaf Major Dickason Blend",
    price: 2.4,
    offerPrice: 2.1,
    stock: 12,
    img: "coffe4.jpg",
    category: "drink",
  },
];
